INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Andorra', NULL, NULL, 'activo', 'assets/flags/ad.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Emiratos Arabes Unidos', NULL, NULL, 'activo', 'assets/flags/ae.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Afganistan', NULL, NULL, 'activo', 'assets/flags/af.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Antigua y Barbuda', NULL, NULL, 'activo', 'assets/flags/ag.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Anguila', NULL, NULL, 'activo', 'assets/flags/ai.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Albania', NULL, NULL, 'activo', 'assets/flags/al.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Armenia', NULL, NULL, 'activo', 'assets/flags/am.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Angola', NULL, NULL, 'activo', 'assets/flags/ao.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Antartida', NULL, NULL, 'activo', 'assets/flags/aq.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Argentina', NULL, NULL, 'activo', 'assets/flags/ar.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Samoa Americana', NULL, NULL, 'activo', 'assets/flags/as.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Austria', NULL, NULL, 'activo', 'assets/flags/at.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Australia', NULL, NULL, 'activo', 'assets/flags/au.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Aruba', NULL, NULL, 'activo', 'assets/flags/aw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Aland', NULL, NULL, 'activo', 'assets/flags/ax.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Azerbaiyan', NULL, NULL, 'activo', 'assets/flags/az.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bosnia y Herzegovina', NULL, NULL, 'activo', 'assets/flags/ba.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Barbados', NULL, NULL, 'activo', 'assets/flags/bb.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Banglades', NULL, NULL, 'activo', 'assets/flags/bd.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Belgica', NULL, NULL, 'activo', 'assets/flags/be.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Burkina Faso', NULL, NULL, 'activo', 'assets/flags/bf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bulgaria', NULL, NULL, 'activo', 'assets/flags/bg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Barein', NULL, NULL, 'activo', 'assets/flags/bh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Burundi', NULL, NULL, 'activo', 'assets/flags/bi.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Benin', NULL, NULL, 'activo', 'assets/flags/bj.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Bartolome', NULL, NULL, 'activo', 'assets/flags/bl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bermudas', NULL, NULL, 'activo', 'assets/flags/bm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Brunei', NULL, NULL, 'activo', 'assets/flags/bn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bolivia', NULL, NULL, 'activo', 'assets/flags/bo.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Caribe neerlandes', NULL, NULL, 'activo', 'assets/flags/bq.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Brasil', NULL, NULL, 'activo', 'assets/flags/br.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bahamas', NULL, NULL, 'activo', 'assets/flags/bs.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Butan', NULL, NULL, 'activo', 'assets/flags/bt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Isla Bouvet', NULL, NULL, 'activo', 'assets/flags/bv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Botsuana', NULL, NULL, 'activo', 'assets/flags/bw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Bielorrusia', NULL, NULL, 'activo', 'assets/flags/by.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Belice', NULL, NULL, 'activo', 'assets/flags/bz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Canada', NULL, NULL, 'activo', 'assets/flags/ca.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Cocos', NULL, NULL, 'activo', 'assets/flags/cc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Republica Democratica del Congo', NULL, NULL, 'activo', 'assets/flags/cd.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Republica Centroafricana', NULL, NULL, 'activo', 'assets/flags/cf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Congo', NULL, NULL, 'activo', 'assets/flags/cg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Suiza', NULL, NULL, 'activo', 'assets/flags/ch.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Costa de Marfil', NULL, NULL, 'activo', 'assets/flags/ci.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Cook', NULL, NULL, 'activo', 'assets/flags/ck.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Chile', NULL, NULL, 'activo', 'assets/flags/cl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Camerun', NULL, NULL, 'activo', 'assets/flags/cm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'China', NULL, NULL, 'activo', 'assets/flags/cn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Colombia', NULL, NULL, 'activo', 'assets/flags/co.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Costa Rica', NULL, NULL, 'activo', 'assets/flags/cr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Cuba', NULL, NULL, 'activo', 'assets/flags/cu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Cabo Verde', NULL, NULL, 'activo', 'assets/flags/cv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Curazao', NULL, NULL, 'activo', 'assets/flags/cw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Isla de Navidad', NULL, NULL, 'activo', 'assets/flags/cx.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Chipre', NULL, NULL, 'activo', 'assets/flags/cy.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Chequia', NULL, NULL, 'activo', 'assets/flags/cz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Alemania', NULL, NULL, 'activo', 'assets/flags/de.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Yibuti', NULL, NULL, 'activo', 'assets/flags/dj.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Dinamarca', NULL, NULL, 'activo', 'assets/flags/dk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Dominica', NULL, NULL, 'activo', 'assets/flags/dm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Republica Dominicana', NULL, NULL, 'activo', 'assets/flags/do.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Argelia', NULL, NULL, 'activo', 'assets/flags/dz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Ecuador', NULL, NULL, 'activo', 'assets/flags/ec.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Estonia', NULL, NULL, 'activo', 'assets/flags/ee.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Egipto', NULL, NULL, 'activo', 'assets/flags/eg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sahara Occidental', NULL, NULL, 'activo', 'assets/flags/eh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Eritrea', NULL, NULL, 'activo', 'assets/flags/er.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Espana', NULL, NULL, 'activo', 'assets/flags/es.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Etiopia', NULL, NULL, 'activo', 'assets/flags/et.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Finlandia', NULL, NULL, 'activo', 'assets/flags/fi.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Fiyi', NULL, NULL, 'activo', 'assets/flags/fj.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Malvinas', NULL, NULL, 'activo', 'assets/flags/fk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Micronesia', NULL, NULL, 'activo', 'assets/flags/fm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Feroe', NULL, NULL, 'activo', 'assets/flags/fo.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Francia', NULL, NULL, 'activo', 'assets/flags/fr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Gabon', NULL, NULL, 'activo', 'assets/flags/ga.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Inglaterra', NULL, NULL, 'activo', 'assets/flags/gb-eng.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Irlanda del Norte', NULL, NULL, 'activo', 'assets/flags/gb-nir.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Escocia', NULL, NULL, 'activo', 'assets/flags/gb-sct.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Gales', NULL, NULL, 'activo', 'assets/flags/gb-wls.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Reino Unido', NULL, NULL, 'activo', 'assets/flags/gb.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Granada', NULL, NULL, 'activo', 'assets/flags/gd.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Georgia', NULL, NULL, 'activo', 'assets/flags/ge.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guayana Francesa', NULL, NULL, 'activo', 'assets/flags/gf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guernesey', NULL, NULL, 'activo', 'assets/flags/gg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Ghana', NULL, NULL, 'activo', 'assets/flags/gh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Gibraltar', NULL, NULL, 'activo', 'assets/flags/gi.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Groenlandia', NULL, NULL, 'activo', 'assets/flags/gl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Gambia', NULL, NULL, 'activo', 'assets/flags/gm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guinea', NULL, NULL, 'activo', 'assets/flags/gn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guadalupe', NULL, NULL, 'activo', 'assets/flags/gp.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guinea Ecuatorial', NULL, NULL, 'activo', 'assets/flags/gq.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Grecia', NULL, NULL, 'activo', 'assets/flags/gr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Georgia del Sur y Sandwich del Sur', NULL, NULL, 'activo', 'assets/flags/gs.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guatemala', NULL, NULL, 'activo', 'assets/flags/gt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guam', NULL, NULL, 'activo', 'assets/flags/gu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guinea-Bisau', NULL, NULL, 'activo', 'assets/flags/gw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Guyana', NULL, NULL, 'activo', 'assets/flags/gy.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'RAE de Hong Kong (China)', NULL, NULL, 'activo', 'assets/flags/hk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Heard y McDonald', NULL, NULL, 'activo', 'assets/flags/hm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Honduras', NULL, NULL, 'activo', 'assets/flags/hn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Croacia', NULL, NULL, 'activo', 'assets/flags/hr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Haiti', NULL, NULL, 'activo', 'assets/flags/ht.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Hungria', NULL, NULL, 'activo', 'assets/flags/hu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Indonesia', NULL, NULL, 'activo', 'assets/flags/id.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Irlanda', NULL, NULL, 'activo', 'assets/flags/ie.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Israel', NULL, NULL, 'activo', 'assets/flags/il.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Isla de Man', NULL, NULL, 'activo', 'assets/flags/im.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'India', NULL, NULL, 'activo', 'assets/flags/in.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Territorio Britanico del Oceano Indico', NULL, NULL, 'activo', 'assets/flags/io.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Irak', NULL, NULL, 'activo', 'assets/flags/iq.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Iran', NULL, NULL, 'activo', 'assets/flags/ir.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islandia', NULL, NULL, 'activo', 'assets/flags/is.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Italia', NULL, NULL, 'activo', 'assets/flags/it.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Jersey', NULL, NULL, 'activo', 'assets/flags/je.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Jamaica', NULL, NULL, 'activo', 'assets/flags/jm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Jordania', NULL, NULL, 'activo', 'assets/flags/jo.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Japon', NULL, NULL, 'activo', 'assets/flags/jp.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kenia', NULL, NULL, 'activo', 'assets/flags/ke.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kirguistan', NULL, NULL, 'activo', 'assets/flags/kg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Camboya', NULL, NULL, 'activo', 'assets/flags/kh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kiribati', NULL, NULL, 'activo', 'assets/flags/ki.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Comoras', NULL, NULL, 'activo', 'assets/flags/km.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Cristobal y Nieves', NULL, NULL, 'activo', 'assets/flags/kn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Corea del Norte', NULL, NULL, 'activo', 'assets/flags/kp.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Corea del Sur', NULL, NULL, 'activo', 'assets/flags/kr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kuwait', NULL, NULL, 'activo', 'assets/flags/kw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Caiman', NULL, NULL, 'activo', 'assets/flags/ky.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kazajistan', NULL, NULL, 'activo', 'assets/flags/kz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Laos', NULL, NULL, 'activo', 'assets/flags/la.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Libano', NULL, NULL, 'activo', 'assets/flags/lb.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Santa Lucia', NULL, NULL, 'activo', 'assets/flags/lc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Liechtenstein', NULL, NULL, 'activo', 'assets/flags/li.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sri Lanka', NULL, NULL, 'activo', 'assets/flags/lk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Liberia', NULL, NULL, 'activo', 'assets/flags/lr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Lesoto', NULL, NULL, 'activo', 'assets/flags/ls.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Lituania', NULL, NULL, 'activo', 'assets/flags/lt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Luxemburgo', NULL, NULL, 'activo', 'assets/flags/lu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Letonia', NULL, NULL, 'activo', 'assets/flags/lv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Libia', NULL, NULL, 'activo', 'assets/flags/ly.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Marruecos', NULL, NULL, 'activo', 'assets/flags/ma.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Monaco', NULL, NULL, 'activo', 'assets/flags/mc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Moldavia', NULL, NULL, 'activo', 'assets/flags/md.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Montenegro', NULL, NULL, 'activo', 'assets/flags/me.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Martin', NULL, NULL, 'activo', 'assets/flags/mf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Madagascar', NULL, NULL, 'activo', 'assets/flags/mg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Marshall', NULL, NULL, 'activo', 'assets/flags/mh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Macedonia del Norte', NULL, NULL, 'activo', 'assets/flags/mk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mali', NULL, NULL, 'activo', 'assets/flags/ml.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Myanmar (Birmania)', NULL, NULL, 'activo', 'assets/flags/mm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mongolia', NULL, NULL, 'activo', 'assets/flags/mn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'RAE de Macao (China)', NULL, NULL, 'activo', 'assets/flags/mo.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Marianas del Norte', NULL, NULL, 'activo', 'assets/flags/mp.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Martinica', NULL, NULL, 'activo', 'assets/flags/mq.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mauritania', NULL, NULL, 'activo', 'assets/flags/mr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Montserrat', NULL, NULL, 'activo', 'assets/flags/ms.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Malta', NULL, NULL, 'activo', 'assets/flags/mt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mauricio', NULL, NULL, 'activo', 'assets/flags/mu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Maldivas', NULL, NULL, 'activo', 'assets/flags/mv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Malaui', NULL, NULL, 'activo', 'assets/flags/mw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mexico', NULL, NULL, 'activo', 'assets/flags/mx.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Malasia', NULL, NULL, 'activo', 'assets/flags/my.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mozambique', NULL, NULL, 'activo', 'assets/flags/mz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Namibia', NULL, NULL, 'activo', 'assets/flags/na.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nueva Caledonia', NULL, NULL, 'activo', 'assets/flags/nc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Niger', NULL, NULL, 'activo', 'assets/flags/ne.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Isla Norfolk', NULL, NULL, 'activo', 'assets/flags/nf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nigeria', NULL, NULL, 'activo', 'assets/flags/ng.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nicaragua', NULL, NULL, 'activo', 'assets/flags/ni.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Paises Bajos', NULL, NULL, 'activo', 'assets/flags/nl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Noruega', NULL, NULL, 'activo', 'assets/flags/no.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nepal', NULL, NULL, 'activo', 'assets/flags/np.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nauru', NULL, NULL, 'activo', 'assets/flags/nr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Niue', NULL, NULL, 'activo', 'assets/flags/nu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Nueva Zelanda', NULL, NULL, 'activo', 'assets/flags/nz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Oman', NULL, NULL, 'activo', 'assets/flags/om.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Panama', NULL, NULL, 'activo', 'assets/flags/pa.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Peru', NULL, NULL, 'activo', 'assets/flags/pe.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Polinesia Francesa', NULL, NULL, 'activo', 'assets/flags/pf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Papua Nueva Guinea', NULL, NULL, 'activo', 'assets/flags/pg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Filipinas', NULL, NULL, 'activo', 'assets/flags/ph.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Pakistan', NULL, NULL, 'activo', 'assets/flags/pk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Polonia', NULL, NULL, 'activo', 'assets/flags/pl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Pedro y Miquelon', NULL, NULL, 'activo', 'assets/flags/pm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Pitcairn', NULL, NULL, 'activo', 'assets/flags/pn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Puerto Rico', NULL, NULL, 'activo', 'assets/flags/pr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Territorios Palestinos', NULL, NULL, 'activo', 'assets/flags/ps.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Portugal', NULL, NULL, 'activo', 'assets/flags/pt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Palaos', NULL, NULL, 'activo', 'assets/flags/pw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Paraguay', NULL, NULL, 'activo', 'assets/flags/py.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Catar', NULL, NULL, 'activo', 'assets/flags/qa.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Reunion', NULL, NULL, 'activo', 'assets/flags/re.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Rumania', NULL, NULL, 'activo', 'assets/flags/ro.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Serbia', NULL, NULL, 'activo', 'assets/flags/rs.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Rusia', NULL, NULL, 'activo', 'assets/flags/ru.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Ruanda', NULL, NULL, 'activo', 'assets/flags/rw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Arabia Saudi', NULL, NULL, 'activo', 'assets/flags/sa.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Salomon', NULL, NULL, 'activo', 'assets/flags/sb.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Seychelles', NULL, NULL, 'activo', 'assets/flags/sc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sudan', NULL, NULL, 'activo', 'assets/flags/sd.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Suecia', NULL, NULL, 'activo', 'assets/flags/se.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Singapur', NULL, NULL, 'activo', 'assets/flags/sg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Santa Elena', NULL, NULL, 'activo', 'assets/flags/sh.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Eslovenia', NULL, NULL, 'activo', 'assets/flags/si.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Svalbard y Jan Mayen', NULL, NULL, 'activo', 'assets/flags/sj.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Eslovaquia', NULL, NULL, 'activo', 'assets/flags/sk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sierra Leona', NULL, NULL, 'activo', 'assets/flags/sl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Marino', NULL, NULL, 'activo', 'assets/flags/sm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Senegal', NULL, NULL, 'activo', 'assets/flags/sn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Somalia', NULL, NULL, 'activo', 'assets/flags/so.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Surinam', NULL, NULL, 'activo', 'assets/flags/sr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sudan del Sur', NULL, NULL, 'activo', 'assets/flags/ss.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Santo Tome y Principe', NULL, NULL, 'activo', 'assets/flags/st.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'El Salvador', NULL, NULL, 'activo', 'assets/flags/sv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sint Maarten', NULL, NULL, 'activo', 'assets/flags/sx.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Siria', NULL, NULL, 'activo', 'assets/flags/sy.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Esuatini', NULL, NULL, 'activo', 'assets/flags/sz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Turcas y Caicos', NULL, NULL, 'activo', 'assets/flags/tc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Chad', NULL, NULL, 'activo', 'assets/flags/td.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Territorios Australes Franceses', NULL, NULL, 'activo', 'assets/flags/tf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Togo', NULL, NULL, 'activo', 'assets/flags/tg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tailandia', NULL, NULL, 'activo', 'assets/flags/th.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tayikistan', NULL, NULL, 'activo', 'assets/flags/tj.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tokelau', NULL, NULL, 'activo', 'assets/flags/tk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Timor-Leste', NULL, NULL, 'activo', 'assets/flags/tl.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Turkmenistan', NULL, NULL, 'activo', 'assets/flags/tm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tunez', NULL, NULL, 'activo', 'assets/flags/tn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tonga', NULL, NULL, 'activo', 'assets/flags/to.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Turquia', NULL, NULL, 'activo', 'assets/flags/tr.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Trinidad y Tobago', NULL, NULL, 'activo', 'assets/flags/tt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tuvalu', NULL, NULL, 'activo', 'assets/flags/tv.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Taiwan', NULL, NULL, 'activo', 'assets/flags/tw.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Tanzania', NULL, NULL, 'activo', 'assets/flags/tz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Ucrania', NULL, NULL, 'activo', 'assets/flags/ua.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Uganda', NULL, NULL, 'activo', 'assets/flags/ug.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas menores alejadas de EE. UU.', NULL, NULL, 'activo', 'assets/flags/um.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Estados Unidos', NULL, NULL, 'activo', 'assets/flags/us.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Uruguay', NULL, NULL, 'activo', 'assets/flags/uy.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Uzbekistan', NULL, NULL, 'activo', 'assets/flags/uz.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Ciudad del Vaticano', NULL, NULL, 'activo', 'assets/flags/va.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'San Vicente y las Granadinas', NULL, NULL, 'activo', 'assets/flags/vc.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Venezuela', NULL, NULL, 'activo', 'assets/flags/ve.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Virgenes Britanicas', NULL, NULL, 'activo', 'assets/flags/vg.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Islas Virgenes de EE. UU.', NULL, NULL, 'activo', 'assets/flags/vi.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Vietnam', NULL, NULL, 'activo', 'assets/flags/vn.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Vanuatu', NULL, NULL, 'activo', 'assets/flags/vu.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Wallis y Futuna', NULL, NULL, 'activo', 'assets/flags/wf.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Samoa', NULL, NULL, 'activo', 'assets/flags/ws.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Kosovo', NULL, NULL, 'activo', 'assets/flags/xk.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Yemen', NULL, NULL, 'activo', 'assets/flags/ye.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Mayotte', NULL, NULL, 'activo', 'assets/flags/yt.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Sudafrica', NULL, NULL, 'activo', 'assets/flags/za.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Zambia', NULL, NULL, 'activo', 'assets/flags/zm.png');
INSERT INTO `destino` (`id_destino`, `pais`, `ciudad`, `descripcion_general`, `estado`, `bandera_path`) VALUES (NULL, 'Zimbabue', NULL, NULL, 'activo', 'assets/flags/zw.png');
